name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v2

      - name: Instalar dependencias
        run: |
          npm install

      - name: Executar testes
        run: |
          npm run test
